name: Security Test CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  issues: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start App in Background
      run: |
        nohup npm start &
        sleep 5

    - name: Run ZAP Baseline Scan Manually
      run: |
        docker run --network=host \
        -v ${{ github.workspace }}:/zap/wrk/:rw \
        ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
        -t http://localhost:3000 \
        -J zap-report.json \
        -w zap-report.md \
        -r zap-report.html || true

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
