name: Security Test CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  issues: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start App in Background
      run: |
        nohup npm start &
        sleep 5

    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.9.0
      with:
        target: 'http://localhost:3000'
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: ghcr.io/zaproxy/zaproxy:stable
        issue_title: ZAP Scan Baseline Report
        fail_action: false
        allow_issue_writing: true
        artifact_name: zap-scan-report

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
